import type { Metadata, Viewport } from "next";
import TopNav from "@/components/TopNav";
import DotDistortionBackground from "@/components/DotDistortionBackground";
import ReferralCapture from "@/components/ReferralCapture";
import MotionLayer from "@/components/MotionLayer";
import CommandSearchLoader from "@/components/CommandSearchLoader";
import Toaster from "@/components/Toaster";
import PwaVitals from "@/components/PwaVitals";
import CookieConsent from "@/components/CookieConsent";
import HtmlLangSync from "@/components/HtmlLangSync";
import GoogleAnalytics from "@/components/GoogleAnalytics";
import ErrorMonitor from "@/components/ErrorMonitor";
import { SITE_URL, SITE_NAME, SITE_TAGLINE, SITE_DESCRIPTION, jsonLd } from "@/lib/seo";
import { organizationLd } from "@/lib/operator";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import "./globals.css";

/* The families keep their REAL names — the canvas tools (promo film, AI
   generators, QR studio, poster maker) set ctx.font = "…px Unbounded /
   Space Mono / Inter", which a next/font hashed family name would break. So
   rather than next/font they are self-hosted as plain @font-face rules in
   app/fonts.css, generated by scripts/fetch-fonts.mjs.

   They used to come from fonts.googleapis.com via <link rel="stylesheet">.
   That put two third-party origins in front of first paint: the font file was
   not discoverable until our own CSS had loaded and the Google stylesheet had
   parsed, which measured 2637 ms for the LCP font on the homepage and 615 ms
   on a tool page — and the LCP element is a paragraph of text on every
   template. Same-origin plus the preload below, it starts at t=0 instead.

   Bricolage Grotesque has no cyrillic subset, so RU/UZ body text falls through
   to Inter; both are self-hosted with Google's own unicode-range blocks intact
   so each visitor still downloads only the subsets their page renders. */
const LCP_FONT = "/fonts/bricolage-grotesque-normal-300-latin.woff2";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  verification: { yandex: "473ef26af7264e86" },
  title: {
    default: `${SITE_NAME} — ${SITE_TAGLINE}`,
    template: `%s | ${SITE_NAME}`,
  },
  description: SITE_DESCRIPTION,
  applicationName: SITE_NAME,
  keywords: [
    "QR code generator", "free QR code", "dynamic QR code", "QR code with logo",
    "PDF tools", "merge PDF", "split PDF", "compress PDF", "PDF to Word", "PDF to JPG",
    "OCR PDF", "sign PDF", "image tools", "remove background", "WiFi QR code", "vCard QR",
  ],
  authors: [{ name: SITE_NAME }],
  alternates: { canonical: SITE_URL },
  openGraph: {
    type: "website",
    url: SITE_URL,
    siteName: SITE_NAME,
    title: `${SITE_NAME} — ${SITE_TAGLINE}`,
    description: SITE_DESCRIPTION,
    // OG/Twitter images are generated by app/opengraph-image.tsx (no static asset needed).
  },
  twitter: {
    card: "summary_large_image",
    title: `${SITE_NAME} — ${SITE_TAGLINE}`,
    description: SITE_DESCRIPTION,
  },
  robots: { index: true, follow: true, googleBot: { index: true, follow: true, "max-image-preview": "large" } },
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#ffffff" },
    { media: "(prefers-color-scheme: dark)", color: "#0b0b12" },
  ],
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      data-scroll-behavior="smooth"
      className="h-full antialiased"
    >
      <head>
        {/* Fonts first, and discoverable by the preload scanner. Only the one
            file that body and display text paint in is preloaded — the rest are
            declared in app/fonts.css and fetched on demand by unicode-range. */}
        <link rel="preload" as="font" type="font/woff2" href={LCP_FONT} crossOrigin="anonymous" />
        {/* Google Consent Mode v2 — default DENIED until the user opts in.
            Must run before AdSense/GA so no ad/analytics storage is set
            without consent (GDPR / AdSense EEA requirement).

            The stored value is a PLAIN string ("granted"/"denied") — that is what
            CookieConsent writes. This script used to JSON.parse it, which throws
            on `granted`, so the catch reset every returning visitor to denied and
            the banner (which compares the raw string) stayed hidden and never
            issued a consent update: accepted consent silently died after the
            first page view.

            It also sets data-consent="pending" on <html> before first paint, so
            the banner can ship in the server HTML and be revealed by CSS instead
            of mounting after hydration — it is a 354x81 block of text at the
            bottom of the viewport, i.e. the LCP element on every template, and
            mounting it late put 2.25 s of element render delay in front of LCP. */}
        <script
          // eslint-disable-next-line react/no-danger
          dangerouslySetInnerHTML={{
            __html: `window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}window.gtag=window.gtag||gtag;var c=null;try{c=localStorage.getItem("qrix_consent")}catch(e){}var v=c==="granted"?"granted":"denied";if(c!=="granted"&&c!=="denied"){document.documentElement.setAttribute("data-consent","pending")}gtag("consent","default",{ad_storage:v,ad_user_data:v,ad_personalization:v,analytics_storage:v,functionality_storage:"granted",security_storage:"granted",wait_for_update:500});`,
          }}
        />
        {/* Google AdSense loader — only injected once the publisher id is configured */}
        {process.env.NEXT_PUBLIC_ADSENSE_CLIENT && (
          // eslint-disable-next-line @next/next/no-sync-scripts
          <script
            async
            src={`https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=${process.env.NEXT_PUBLIC_ADSENSE_CLIENT}`}
            crossOrigin="anonymous"
          />
        )}
        {/* canonical host — runs before anything else. The service worker's page
            cache can swallow the www→apex redirect and leave the page running on
            www; every same-origin API fetch then hits the domain redirect (a
            "Redirecting…" body, not JSON) and fails — which is how a PIN QR came
            out unprotected. If we're on the canonical host's www alias, replace
            to the canonical origin. Preview deploys (*.vercel.app) never match. */}
        <script
          // eslint-disable-next-line react/no-danger
          dangerouslySetInnerHTML={{
            __html: `try{var q=new URL(${JSON.stringify(SITE_URL)});if(location.hostname==="www."+q.hostname){location.replace(q.origin+location.pathname+location.search+location.hash)}}catch(e){}`,
          }}
        />
        {/* theme init — runs before paint to avoid flash */}
        <script
          // eslint-disable-next-line react/no-danger
          dangerouslySetInnerHTML={{
            // QRix is dark-only. The light theme was removed — note this script used to
            // ADD `light` whenever no theme was stored (and in its catch), so every new
            // visitor actually landed in light mode on a design built for dark.
            __html: `try{document.documentElement.classList.remove("light");localStorage.removeItem("theme");var s=JSON.parse(localStorage.getItem("qrix_settings")||"{}");if(s.performance||s.animations===false){document.documentElement.classList.add("qx-perf")}}catch(e){}`,
          }}
        />
        {/* Organization + WebSite structured data */}
        <script
          type="application/ld+json"
          // eslint-disable-next-line react/no-danger
          dangerouslySetInnerHTML={jsonLd([
            // Organization now carries founder/sameAs/contactPoint and an @id, so
            // the Person on /about and every article byline resolve to the same
            // two entities site-wide instead of anonymous copies (M145).
            // logo stays /icon.png: /icon (the old dynamic route) 404s since the
            // icon became a static file.
            organizationLd(),
            { "@context": "https://schema.org", "@type": "WebSite", "@id": `${SITE_URL}/#website`, name: SITE_NAME, url: SITE_URL, publisher: { "@id": `${SITE_URL}/#organization` }, potentialAction: { "@type": "SearchAction", target: `${SITE_URL}/qr-tools?q={search_term_string}`, "query-input": "required name=search_term_string" } },
          ])}
        />
      </head>
      <body className="min-h-full flex flex-col">
        <HtmlLangSync />
        <a href="#main" className="qx-skip-link">Skip to content</a>
        {/* Бутун сайт фони — barcha sahifalarda chiqadi */}
        <DotDistortionBackground />
        <ReferralCapture />
        <MotionLayer />
        <CommandSearchLoader />
        <Toaster />
        <PwaVitals />
        <TopNav />
        <div id="main" tabIndex={-1} className="contents">{children}</div>
        <CookieConsent />
        <ErrorMonitor />
        {/* GA4 measurement ID is public by design; env can override it */}
        <GoogleAnalytics id={process.env.NEXT_PUBLIC_GA_ID || "G-XKW8P2LRY0"} />
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
