import type { Metadata, Viewport } from "next";
import TopNav from "@/components/TopNav";
import DotDistortionBackground from "@/components/DotDistortionBackground";
import ReferralCapture from "@/components/ReferralCapture";
import MotionLayer from "@/components/MotionLayer";
import CommandSearch from "@/components/CommandSearch";
import Toaster from "@/components/Toaster";
import PwaVitals from "@/components/PwaVitals";
import CookieConsent from "@/components/CookieConsent";
import HtmlLangSync from "@/components/HtmlLangSync";
import GoogleAnalytics from "@/components/GoogleAnalytics";
import ErrorMonitor from "@/components/ErrorMonitor";
import { SITE_URL, SITE_NAME, SITE_TAGLINE, SITE_DESCRIPTION, jsonLd } from "@/lib/seo";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import "./globals.css";

/* The 8 display/mono families are loaded from Google Fonts by their REAL family
   names, because the canvas tools (promo film, AI generators, QR studio) set
   ctx.font = "…px SUSE / Poppins / Unbounded / Space Mono", which a next/font
   hashed family name would break. They are pulled in with a <link> + preconnect
   in <head> rather than a CSS @import: an @import inside globals.css is only
   discovered after the stylesheet parses, so it blocks render late. Geist was
   previously also self-hosted via next/font but never referenced by any rule —
   that was a pure double-load and has been removed. */
const GOOGLE_FONTS_HREF =
  "https://fonts.googleapis.com/css2?family=SUSE:wght@500;600;700;800&family=Poppins:wght@700;800&family=Inter:wght@400;500;600;700;800&family=Space+Mono:ital,wght@0,400;0,700;1,400&family=Bricolage+Grotesque:opsz,wght@12..96,300;12..96,400;12..96,500;12..96,600;12..96,700;12..96,800&family=Anton&family=Oswald:wght@600;700&family=Unbounded:wght@700;800;900&display=swap";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  verification: { yandex: "473ef26af7264e86" },
  title: {
    default: `${SITE_NAME} — ${SITE_TAGLINE}`,
    template: `%s | ${SITE_NAME}`,
  },
  description: SITE_DESCRIPTION,
  applicationName: SITE_NAME,
  keywords: [
    "QR code generator", "free QR code", "dynamic QR code", "QR code with logo",
    "PDF tools", "merge PDF", "split PDF", "compress PDF", "PDF to Word", "PDF to JPG",
    "OCR PDF", "sign PDF", "image tools", "remove background", "WiFi QR code", "vCard QR",
  ],
  authors: [{ name: SITE_NAME }],
  alternates: { canonical: SITE_URL },
  openGraph: {
    type: "website",
    url: SITE_URL,
    siteName: SITE_NAME,
    title: `${SITE_NAME} — ${SITE_TAGLINE}`,
    description: SITE_DESCRIPTION,
    // OG/Twitter images are generated by app/opengraph-image.tsx (no static asset needed).
  },
  twitter: {
    card: "summary_large_image",
    title: `${SITE_NAME} — ${SITE_TAGLINE}`,
    description: SITE_DESCRIPTION,
  },
  robots: { index: true, follow: true, googleBot: { index: true, follow: true, "max-image-preview": "large" } },
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#ffffff" },
    { media: "(prefers-color-scheme: dark)", color: "#0b0b12" },
  ],
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      data-scroll-behavior="smooth"
      className="h-full antialiased"
    >
      <head>
        {/* Fonts first, and discoverable by the preload scanner. */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link rel="stylesheet" href={GOOGLE_FONTS_HREF} />
        {/* Google Consent Mode v2 — default DENIED until the user opts in.
            Must run before AdSense/GA so no ad/analytics storage is set
            without consent (GDPR / AdSense EEA requirement). */}
        <script
          // eslint-disable-next-line react/no-danger
          dangerouslySetInnerHTML={{
            __html: `window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}window.gtag=window.gtag||gtag;try{var c=JSON.parse(localStorage.getItem("qrix_consent")||"null");}catch(e){c=null;}var v=c==="granted"?"granted":"denied";gtag("consent","default",{ad_storage:v,ad_user_data:v,ad_personalization:v,analytics_storage:v,functionality_storage:"granted",security_storage:"granted",wait_for_update:500});`,
          }}
        />
        {/* Google AdSense loader — only injected once the publisher id is configured */}
        {process.env.NEXT_PUBLIC_ADSENSE_CLIENT && (
          // eslint-disable-next-line @next/next/no-sync-scripts
          <script
            async
            src={`https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=${process.env.NEXT_PUBLIC_ADSENSE_CLIENT}`}
            crossOrigin="anonymous"
          />
        )}
        {/* canonical host — runs before anything else. The service worker's page
            cache can swallow the www→apex redirect and leave the page running on
            www; every same-origin API fetch then hits the domain redirect (a
            "Redirecting…" body, not JSON) and fails — which is how a PIN QR came
            out unprotected. If we're on the canonical host's www alias, replace
            to the canonical origin. Preview deploys (*.vercel.app) never match. */}
        <script
          // eslint-disable-next-line react/no-danger
          dangerouslySetInnerHTML={{
            __html: `try{var q=new URL(${JSON.stringify(SITE_URL)});if(location.hostname==="www."+q.hostname){location.replace(q.origin+location.pathname+location.search+location.hash)}}catch(e){}`,
          }}
        />
        {/* theme init — runs before paint to avoid flash */}
        <script
          // eslint-disable-next-line react/no-danger
          dangerouslySetInnerHTML={{
            // QRix is dark-only. The light theme was removed — note this script used to
            // ADD `light` whenever no theme was stored (and in its catch), so every new
            // visitor actually landed in light mode on a design built for dark.
            __html: `try{document.documentElement.classList.remove("light");localStorage.removeItem("theme");var s=JSON.parse(localStorage.getItem("qrix_settings")||"{}");if(s.performance||s.animations===false){document.documentElement.classList.add("qx-perf")}}catch(e){}`,
          }}
        />
        {/* Organization + WebSite structured data */}
        <script
          type="application/ld+json"
          // eslint-disable-next-line react/no-danger
          dangerouslySetInnerHTML={jsonLd([
            { "@context": "https://schema.org", "@type": "Organization", name: SITE_NAME, url: SITE_URL, logo: `${SITE_URL}/icon` },
            { "@context": "https://schema.org", "@type": "WebSite", name: SITE_NAME, url: SITE_URL, potentialAction: { "@type": "SearchAction", target: `${SITE_URL}/qr-tools?q={search_term_string}`, "query-input": "required name=search_term_string" } },
          ])}
        />
      </head>
      <body className="min-h-full flex flex-col">
        <HtmlLangSync />
        <a href="#main" className="qx-skip-link">Skip to content</a>
        {/* Бутун сайт фони — barcha sahifalarda chiqadi */}
        <DotDistortionBackground />
        <ReferralCapture />
        <MotionLayer />
        <CommandSearch />
        <Toaster />
        <PwaVitals />
        <TopNav />
        <div id="main" tabIndex={-1} className="contents">{children}</div>
        <CookieConsent />
        <ErrorMonitor />
        {/* GA4 measurement ID is public by design; env can override it */}
        <GoogleAnalytics id={process.env.NEXT_PUBLIC_GA_ID || "G-XKW8P2LRY0"} />
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
