import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import TopNav from "@/components/TopNav";
import DotDistortionBackground from "@/components/DotDistortionBackground";
import ReferralCapture from "@/components/ReferralCapture";
import MotionLayer from "@/components/MotionLayer";
import CommandSearch from "@/components/CommandSearch";
import Toaster from "@/components/Toaster";
import PwaVitals from "@/components/PwaVitals";
import { SITE_URL, SITE_NAME, SITE_TAGLINE, SITE_DESCRIPTION, jsonLd } from "@/lib/seo";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: `${SITE_NAME} — ${SITE_TAGLINE}`,
    template: `%s | ${SITE_NAME}`,
  },
  description: SITE_DESCRIPTION,
  applicationName: SITE_NAME,
  keywords: [
    "QR code generator", "free QR code", "dynamic QR code", "QR code with logo",
    "PDF tools", "merge PDF", "split PDF", "compress PDF", "PDF to Word", "PDF to JPG",
    "OCR PDF", "sign PDF", "image tools", "remove background", "WiFi QR code", "vCard QR",
  ],
  authors: [{ name: SITE_NAME }],
  alternates: { canonical: SITE_URL },
  openGraph: {
    type: "website",
    url: SITE_URL,
    siteName: SITE_NAME,
    title: `${SITE_NAME} — ${SITE_TAGLINE}`,
    description: SITE_DESCRIPTION,
    // OG/Twitter images are generated by app/opengraph-image.tsx (no static asset needed).
  },
  twitter: {
    card: "summary_large_image",
    title: `${SITE_NAME} — ${SITE_TAGLINE}`,
    description: SITE_DESCRIPTION,
  },
  robots: { index: true, follow: true, googleBot: { index: true, follow: true, "max-image-preview": "large" } },
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#ffffff" },
    { media: "(prefers-color-scheme: dark)", color: "#0b0b12" },
  ],
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      data-scroll-behavior="smooth"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        {/* Google AdSense loader — only injected once the publisher id is configured */}
        {process.env.NEXT_PUBLIC_ADSENSE_CLIENT && (
          // eslint-disable-next-line @next/next/no-sync-scripts
          <script
            async
            src={`https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=${process.env.NEXT_PUBLIC_ADSENSE_CLIENT}`}
            crossOrigin="anonymous"
          />
        )}
        {/* theme init — runs before paint to avoid flash */}
        <script
          // eslint-disable-next-line react/no-danger
          dangerouslySetInnerHTML={{
            __html: `try{if(localStorage.getItem("theme")!=="dark"){document.documentElement.classList.add("light")}var s=JSON.parse(localStorage.getItem("qrix_settings")||"{}");if(s.performance||s.animations===false){document.documentElement.classList.add("qx-perf")}}catch(e){document.documentElement.classList.add("light")}`,
          }}
        />
        {/* Organization + WebSite structured data */}
        <script
          type="application/ld+json"
          // eslint-disable-next-line react/no-danger
          dangerouslySetInnerHTML={jsonLd([
            { "@context": "https://schema.org", "@type": "Organization", name: SITE_NAME, url: SITE_URL, logo: `${SITE_URL}/icon` },
            { "@context": "https://schema.org", "@type": "WebSite", name: SITE_NAME, url: SITE_URL, potentialAction: { "@type": "SearchAction", target: `${SITE_URL}/qr-tools?q={search_term_string}`, "query-input": "required name=search_term_string" } },
          ])}
        />
      </head>
      <body className="min-h-full flex flex-col">
        <a href="#main" className="qx-skip-link">Skip to content</a>
        {/* Бутун сайт фони — barcha sahifalarda chiqadi */}
        <DotDistortionBackground />
        <ReferralCapture />
        <MotionLayer />
        <CommandSearch />
        <Toaster />
        <PwaVitals />
        <TopNav />
        <div id="main" className="contents">{children}</div>
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
