/* GENERATED by scripts/gen-bunny-frames.mjs — do not edit by hand.

   The hero bunny as a scroll-scrubbable image sequence. Frames are cut from
   public/scenes/bunny-hero-live.webm, whose alpha only survives the libvpx decoder,
   and stop at source frame 98: that video flashes white from 3.50s to 4.57s and the
   generator refuses to emit a washed-out frame. */

export const BUNNY_FRAMES = 50;
export const BUNNY_W = 440;
export const BUNNY_H = 770;

/** 1-indexed, zero-padded to three: /scenes/bunny-point/001.webp */
export const bunnyFrameSrc = (i: number) =>
  `/scenes/bunny-point/${String(i + 1).padStart(3, "0")}.webp`;
