// GENERATED by scripts/gen-home-i18n-split.mjs — do not edit by hand.
// Homepage UI copy — de. Reached only through loadHomeUi("de").
import type { HomeUi } from "./types";

const ui: HomeUi = {
  "pageT": {
    "badge": "🚀 Die All-in-One QR-Plattform",
    "h1a": "Erstellen. Verfolgen.",
    "h1b": "Analysieren.",
    "h1c": "Wachsen.",
    "sub": "QRix hilft dir, leistungsstarke QR-Codes für jeden Zweck zu erstellen, jeden Scan in Echtzeit zu verfolgen und dein Business smarter wachsen zu lassen.",
    "cta": "Erstelle deinen ersten QR-Code",
    "demo": "Demo ansehen",
    "rating": "4,9/5 von 2.847+ Nutzern",
    "cardTitle": "Erstelle deinen QR-Code",
    "cardSub": "Schnell, einfach und kostenlos loslegen.",
    "url": "URL",
    "text": "Text",
    "wifi": "WiFi",
    "vcard": "vCard",
    "more": "Mehr",
    "enterUrl": "URL eingeben",
    "enterText": "Text eingeben",
    "ssid": "Netzwerkname (SSID)",
    "password": "Passwort",
    "fullName": "Vollständiger Name",
    "phone": "Telefon",
    "emailL": "E-Mail",
    "org": "Unternehmen",
    "emailTo": "Empfänger-E-Mail",
    "subject": "Betreff",
    "body": "Nachricht",
    "smsPhone": "Telefonnummer",
    "smsMsg": "Nachricht",
    "waPhone": "WhatsApp-Nummer (998...)",
    "waMsg": "Nachricht (optional)",
    "tgUser": "Telegram-Benutzername (ohne @)",
    "pin": "PIN-Schutz hinzufügen",
    "pinOpt": "(optional)",
    "pinPh": "4–10-stelligen PIN eingeben",
    "pinInfo": "Scans erfordern diesen PIN. Erstellt einen geschützten dynamischen Link.",
    "confirmPin": "PIN bestätigen",
    "pinSet": "PIN gesetzt — er wird dem QR-Code hinzugefügt.",
    "generate": "QR-Code erstellen",
    "generating": "Wird erstellt...",
    "yourQr": "Dein QR-Code",
    "dlPng": "PNG herunterladen",
    "dlSvg": "SVG herunterladen",
    "customize": "Design anpassen",
    "protected": "PIN-geschützter Link erstellt:",
    "designTitle": "QR-Design-Studio",
    "qrColor": "QR-Farbe",
    "bgColor": "Hintergrund",
    "size": "Größe",
    "errLevel": "Fehlerkorrektur",
    "logo": "Logo",
    "uploadLogo": "Logo hochladen",
    "removeLogo": "Entfernen",
    "done": "Fertig",
    "statQr": "Erstellte QR-Codes",
    "statScans": "Scans insgesamt",
    "statCountries": "Erreichte Länder",
    "statBiz": "Zufriedene Unternehmen",
    "statUptime": "Verfügbarkeit & Zuverlässigkeit",
    "whyTitle": "Warum",
    "whySub": "Alles, was du brauchst, um QR-Codes zu erstellen, zu verwalten und zu verfolgen",
    "f1": "Echtzeit-Analysen",
    "f1d": "Verfolge Scans, Standorte, Geräte und vieles mehr in Echtzeit.",
    "f2": "Dynamische QR-Codes",
    "f2d": "Ändere dein Ziel jederzeit, ohne den QR-Code zu ändern.",
    "f3": "Erweiterte Sicherheit",
    "f3d": "PIN-Schutz, Ablaufdatum, Limits und Spam-Schutz.",
    "f4": "Schöne Individualisierung",
    "f4d": "Eigene Farben, Logos, Rahmen und einzigartige Designs.",
    "toolsTitle": "Alle Tools an einem Ort",
    "footAbout": "Professioneller QR-Code-Generator mit Echtzeit-Analysen, PDF- und Bild-Tools — alles auf einer Plattform.",
    "footProduct": "Produkt",
    "footTools": "Tools",
    "footContact": "Kontakt",
    "rights": "Alle Rechte vorbehalten."
  },
  "homeFaq": {
    "t": "Häufig gestellte Fragen",
    "s": "Alles, was du vor dem Start wissen solltest."
  },
  "newsletter": {
    "t": "Bleib auf dem Laufenden",
    "s": "Neue Tools, Guides und Wachstumstipps — einmal im Monat, kein Spam.",
    "ph": "you@example.com",
    "btn": "Abonnieren",
    "ok": "Du bist dabei! Schau bald in dein Postfach.",
    "err": "Abo fehlgeschlagen — bitte erneut versuchen."
  },
  "nav": {
    "home": "Startseite",
    "qr": "QR-Tools",
    "pdf": "PDF-Tools",
    "image": "Bild-Tools",
    "dashboard": "Dashboard",
    "pricing": "Preise",
    "blog": "Blog",
    "ai": "AI-Tools",
    "video": "Video-Tools",
    "three": "3D-Tools",
    "signin": "Anmelden",
    "signout": "Abmelden",
    "signup": "Registrieren"
  },
  "faq": [
    {
      "q": "Ist QRix wirklich kostenlos?",
      "a": "Ja – alle 185+ Tools sind kostenlos, ohne Wasserzeichen und ohne Anmeldung. Pro bringt unbegrenzte dynamische QR-Codes, ausführlichere Analysen und ein werbefreies Erlebnis."
    },
    {
      "q": "Werden meine Dateien auf einen Server hochgeladen?",
      "a": "Nein. PDF-, Bild- und QR-Tools laufen vollständig in deinem Browser – deine Dateien verlassen dein Gerät nie."
    },
    {
      "q": "Laufen meine QR-Codes ab?",
      "a": "Statische QR-Codes laufen nie ab. Dynamische QR-Codes bleiben aktiv, solange dein Link existiert, und du kannst ihr Ziel jederzeit ändern."
    },
    {
      "q": "Kann ich mein Logo und meine Markenfarben zu einem QR-Code hinzufügen?",
      "a": "Ja – das Design Studio unterstützt Logos, individuelle Farben, Punktformen und „Scan me\"-Rahmen, während der Code scanbar bleibt."
    },
    {
      "q": "Funktioniert QRix auf dem Smartphone?",
      "a": "Ja – jedes Tool ist responsiv und funktioniert in jedem modernen mobilen Browser. Du kannst QRix über das Browsermenü auch als App installieren."
    },
    {
      "q": "In welchen Formaten kann ich herunterladen?",
      "a": "QR-Codes lassen sich als PNG oder SVG exportieren; PDFs, Bilder und Barcodes werden in ihren nativen Formaten in hoher Qualität exportiert."
    },
    {
      "q": "Kann ich verfolgen, wer meinen QR-Code scannt?",
      "a": "Mit einem dynamischen QR-Code erhältst du Scan-Analysen in Echtzeit – Gesamtzahlen, Zeitpunkt, ungefährer Standort und Geräte – direkt in deinem Dashboard."
    },
    {
      "q": "Wie unterscheidet sich QRix von anderen QR-Generatoren?",
      "a": "Es ist eine komplette Toolbox: 30+ QR-Typen, Barcode-Studio, Link-in-Bio-Seiten, Poster-Maker sowie vollständige PDF- und Bild-Toolkits – privat, schnell und kostenlos."
    }
  ]
};

export default ui;
