// GENERATED by scripts/gen-home-i18n-split.mjs — do not edit by hand.
// Homepage UI copy — es. Reached only through loadHomeUi("es").
import type { HomeUi } from "./types";

const ui: HomeUi = {
  "pageT": {
    "badge": "🚀 La plataforma QR todo en uno",
    "h1a": "Genera. Rastrea.",
    "h1b": "Analiza.",
    "h1c": "Crece.",
    "sub": "185+ herramientas gratis en tu navegador — códigos QR con analíticas en vivo, conversores de PDF e imágenes, generadores de IA, vídeo y 3D. Nada sale de tu dispositivo.",
    "cta": "Crea tu primer código QR",
    "demo": "Ver demo",
    "rating": "4,9/5 de más de 2.847 usuarios",
    "cardTitle": "Crea tu código QR",
    "cardSub": "Es rápido, fácil y gratis para empezar.",
    "url": "URL",
    "text": "Texto",
    "wifi": "WiFi",
    "vcard": "vCard",
    "more": "Más",
    "enterUrl": "Introduce tu URL",
    "enterText": "Introduce tu texto",
    "ssid": "Nombre de red (SSID)",
    "password": "Contraseña",
    "fullName": "Nombre completo",
    "phone": "Teléfono",
    "emailL": "Correo",
    "org": "Empresa",
    "emailTo": "Correo del destinatario",
    "subject": "Asunto",
    "body": "Mensaje",
    "smsPhone": "Número de teléfono",
    "smsMsg": "Mensaje",
    "waPhone": "Número de WhatsApp (998...)",
    "waMsg": "Mensaje (opcional)",
    "tgUser": "Usuario de Telegram (sin @)",
    "pin": "Añadir protección con PIN",
    "pinOpt": "(opcional)",
    "pinPh": "Introduce un PIN de 4–10 dígitos",
    "pinInfo": "Los escaneos requerirán este PIN. Crea un enlace dinámico protegido.",
    "confirmPin": "Confirmar PIN",
    "pinSet": "PIN establecido — se añadirá al código QR.",
    "generate": "Generar código QR",
    "generating": "Creando...",
    "yourQr": "Tu código QR",
    "dlPng": "Descargar PNG",
    "dlSvg": "Descargar SVG",
    "customize": "Personalizar diseño",
    "protected": "Enlace protegido con PIN creado:",
    "designTitle": "Estudio de diseño QR",
    "qrColor": "Color del QR",
    "bgColor": "Fondo",
    "size": "Tamaño",
    "errLevel": "Corrección de errores",
    "logo": "Logo",
    "uploadLogo": "Subir logo",
    "removeLogo": "Quitar",
    "done": "Listo",
    "statQr": "Códigos QR creados",
    "statScans": "Escaneos totales",
    "statCountries": "Países alcanzados",
    "statBiz": "Negocios satisfechos",
    "statUptime": "Disponibilidad y fiabilidad",
    "whyTitle": "Por qué",
    "whySub": "Todo lo que necesitas para crear, gestionar y rastrear códigos QR",
    "f1": "Analíticas en tiempo real",
    "f1d": "Rastrea escaneos, ubicaciones, dispositivos y mucho más en tiempo real.",
    "f2": "Códigos QR dinámicos",
    "f2d": "Actualiza tu destino cuando quieras sin cambiar el código QR.",
    "f3": "Seguridad avanzada",
    "f3d": "Protección con PIN, caducidad, límites y antispam.",
    "f4": "Personalización elegante",
    "f4d": "Colores, logos, marcos y diseños únicos personalizados.",
    "toolsTitle": "Todas las herramientas en un solo lugar",
    "footAbout": "Generador profesional de códigos QR con analíticas en tiempo real, herramientas de PDF e imágenes — todo en una plataforma.",
    "footProduct": "Producto",
    "footTools": "Herramientas",
    "footContact": "Contacto",
    "rights": "Todos los derechos reservados."
  },
  "homeFaq": {
    "t": "Preguntas frecuentes",
    "s": "Todo lo que quizás quieras saber antes de empezar."
  },
  "newsletter": {
    "t": "Mantente al día",
    "s": "Nuevas herramientas, guías y consejos de crecimiento — una vez al mes, sin spam.",
    "ph": "you@example.com",
    "btn": "Suscribirse",
    "ok": "¡Listo! Revisa tu bandeja pronto.",
    "err": "No se pudo suscribir — inténtalo de nuevo."
  },
  "nav": {
    "home": "Inicio",
    "qr": "Herramientas QR",
    "pdf": "Herramientas PDF",
    "image": "Herramientas de imagen",
    "dashboard": "Panel",
    "pricing": "Precios",
    "blog": "Blog",
    "ai": "Herramientas de IA",
    "video": "Herramientas de vídeo",
    "three": "Herramientas 3D",
    "signin": "Iniciar sesión",
    "signout": "Cerrar sesión",
    "signup": "Registrarse"
  },
  "faq": [
    {
      "q": "¿QRix es realmente gratis?",
      "a": "Sí: las más de 55 herramientas son gratuitas, sin marca de agua y sin registro. Pro añade códigos QR dinámicos ilimitados, analíticas más completas y una experiencia sin anuncios."
    },
    {
      "q": "¿Mis archivos se suben a un servidor?",
      "a": "No. Las herramientas de PDF, imágenes y QR funcionan por completo en tu navegador: tus archivos nunca salen de tu dispositivo."
    },
    {
      "q": "¿Caducan mis códigos QR?",
      "a": "Los códigos QR estáticos no caducan nunca. Los QR dinámicos siguen activos mientras exista tu enlace, y puedes cambiar su destino cuando quieras."
    },
    {
      "q": "¿Puedo añadir mi logo y los colores de mi marca a un código QR?",
      "a": "Sí: el Design Studio admite logos, colores personalizados, formas de puntos y marcos 'Scan me' sin que el código deje de ser escaneable."
    },
    {
      "q": "¿Funciona QRix en el móvil?",
      "a": "Sí: todas las herramientas son responsive y funcionan en cualquier navegador móvil moderno. Además, puedes instalar QRix como app desde el menú de tu navegador."
    },
    {
      "q": "¿En qué formatos puedo descargar?",
      "a": "Los códigos QR se exportan en PNG o SVG; los PDF, las imágenes y los códigos de barras se exportan en sus formatos nativos de alta calidad."
    },
    {
      "q": "¿Puedo saber quién escanea mi código QR?",
      "a": "Con un código QR dinámico obtienes analíticas de escaneo en tiempo real (totales, hora, ubicación aproximada y dispositivos) directamente en tu panel."
    },
    {
      "q": "¿En qué se diferencia QRix de otros generadores de QR?",
      "a": "Es una caja de herramientas completa: más de 30 tipos de QR, estudio de códigos de barras, páginas link-in-bio, creador de pósters, además de kits completos de PDF e imágenes; privado, rápido y gratis."
    }
  ]
};

export default ui;
