// GENERATED by scripts/gen-home-i18n-split.mjs — do not edit by hand.
// Homepage UI copy — fr. Reached only through loadHomeUi("fr").
import type { HomeUi } from "./types";

const ui: HomeUi = {
  "pageT": {
    "badge": "🚀 La plateforme QR tout-en-un",
    "h1a": "Générez. Suivez.",
    "h1b": "Analysez.",
    "h1c": "Développez.",
    "sub": "QRix vous aide à créer des QR codes puissants pour tous vos besoins, à suivre chaque scan en temps réel et à développer votre activité plus intelligemment.",
    "cta": "Créez votre premier QR code",
    "demo": "Voir la démo",
    "rating": "4,9/5 par 2 847+ utilisateurs",
    "cardTitle": "Créez votre QR code",
    "cardSub": "Rapide, simple et gratuit pour démarrer.",
    "url": "URL",
    "text": "Texte",
    "wifi": "WiFi",
    "vcard": "vCard",
    "more": "Plus",
    "enterUrl": "Saisissez votre URL",
    "enterText": "Saisissez votre texte",
    "ssid": "Nom du réseau (SSID)",
    "password": "Mot de passe",
    "fullName": "Nom complet",
    "phone": "Téléphone",
    "emailL": "E-mail",
    "org": "Entreprise",
    "emailTo": "E-mail du destinataire",
    "subject": "Objet",
    "body": "Message",
    "smsPhone": "Numéro de téléphone",
    "smsMsg": "Message",
    "waPhone": "Numéro WhatsApp (998...)",
    "waMsg": "Message (facultatif)",
    "tgUser": "Nom d'utilisateur Telegram (sans @)",
    "pin": "Ajouter une protection PIN",
    "pinOpt": "(facultatif)",
    "pinPh": "Saisissez un PIN de 4 à 10 chiffres",
    "pinInfo": "Les scans exigeront ce PIN. Un lien dynamique protégé est créé.",
    "confirmPin": "Confirmez le PIN",
    "pinSet": "PIN défini — il sera ajouté au QR code.",
    "generate": "Générer le QR code",
    "generating": "Création...",
    "yourQr": "Votre QR code",
    "dlPng": "Télécharger le PNG",
    "dlSvg": "Télécharger le SVG",
    "customize": "Personnaliser le design",
    "protected": "Lien protégé par PIN créé :",
    "designTitle": "Studio de design QR",
    "qrColor": "Couleur du QR",
    "bgColor": "Arrière-plan",
    "size": "Taille",
    "errLevel": "Correction d'erreurs",
    "logo": "Logo",
    "uploadLogo": "Importer un logo",
    "removeLogo": "Supprimer",
    "done": "Terminé",
    "statQr": "QR codes créés",
    "statScans": "Scans au total",
    "statCountries": "Pays atteints",
    "statBiz": "Entreprises satisfaites",
    "statUptime": "Disponibilité et fiabilité",
    "whyTitle": "Pourquoi",
    "whySub": "Tout ce qu'il faut pour créer, gérer et suivre vos QR codes",
    "f1": "Analyses en temps réel",
    "f1d": "Suivez les scans, les lieux, les appareils et bien plus en temps réel.",
    "f2": "QR codes dynamiques",
    "f2d": "Modifiez votre destination à tout moment sans changer le QR code.",
    "f3": "Sécurité avancée",
    "f3d": "Protection par PIN, expiration, limites et anti-spam.",
    "f4": "Personnalisation soignée",
    "f4d": "Couleurs, logos, cadres et designs uniques sur mesure.",
    "toolsTitle": "Tous les outils au même endroit",
    "footAbout": "Générateur de QR codes professionnel avec analyses en temps réel, outils PDF et image — le tout sur une seule plateforme.",
    "footProduct": "Produit",
    "footTools": "Outils",
    "footContact": "Contact",
    "rights": "Tous droits réservés."
  },
  "homeFaq": {
    "t": "Questions fréquentes",
    "s": "Tout ce que vous devez savoir avant de commencer."
  },
  "newsletter": {
    "t": "Restez informé",
    "s": "Nouveaux outils, guides et astuces de croissance — une fois par mois, sans spam.",
    "ph": "you@example.com",
    "btn": "S'abonner",
    "ok": "C'est fait ! Consultez bientôt votre boîte de réception.",
    "err": "Échec de l'inscription — réessayez."
  },
  "nav": {
    "home": "Accueil",
    "qr": "Outils QR",
    "pdf": "Outils PDF",
    "image": "Outils image",
    "dashboard": "Tableau de bord",
    "pricing": "Tarifs",
    "blog": "Blog",
    "ai": "Outils IA",
    "video": "Outils vidéo",
    "three": "Outils 3D",
    "signin": "Connexion",
    "signout": "Déconnexion",
    "signup": "Inscription"
  },
  "faq": [
    {
      "q": "QRix est-il vraiment gratuit ?",
      "a": "Oui — les 185+ outils sont gratuits, sans filigrane et sans inscription. La version Pro ajoute des QR codes dynamiques illimités, des analyses plus poussées et une expérience sans publicité."
    },
    {
      "q": "Mes fichiers sont-ils envoyés sur un serveur ?",
      "a": "Non. Les outils PDF, image et QR fonctionnent entièrement dans votre navigateur — vos fichiers ne quittent jamais votre appareil."
    },
    {
      "q": "Mes QR codes expirent-ils ?",
      "a": "Les QR codes statiques n'expirent jamais. Les QR codes dynamiques restent actifs tant que votre lien existe, et vous pouvez en modifier la destination à tout moment."
    },
    {
      "q": "Puis-je ajouter mon logo et les couleurs de ma marque à un QR code ?",
      "a": "Oui — le Design Studio prend en charge les logos, les couleurs personnalisées, les formes de points et les cadres « Scan me », tout en gardant le code parfaitement scannable."
    },
    {
      "q": "QRix fonctionne-t-il sur mobile ?",
      "a": "Oui — chaque outil est responsive et fonctionne dans n'importe quel navigateur mobile moderne. Vous pouvez aussi installer QRix comme une application depuis le menu de votre navigateur."
    },
    {
      "q": "Quels formats puis-je télécharger ?",
      "a": "Les QR codes s'exportent en PNG ou SVG ; les PDF, images et codes-barres s'exportent dans leurs formats natifs de haute qualité."
    },
    {
      "q": "Puis-je savoir qui scanne mon QR code ?",
      "a": "Avec un QR code dynamique, vous obtenez des analyses de scans en temps réel — totaux, horaires, localisation approximative et appareils — directement dans votre tableau de bord."
    },
    {
      "q": "En quoi QRix se distingue-t-il des autres générateurs de QR ?",
      "a": "C'est une boîte à outils complète : plus de 30 types de QR, un studio de codes-barres, des pages link-in-bio, un créateur d'affiches, ainsi que des kits complets pour PDF et images — privé, rapide et gratuit."
    }
  ]
};

export default ui;
