// GENERATED by scripts/gen-home-i18n-split.mjs — do not edit by hand.
// Homepage UI copy — id. Reached only through loadHomeUi("id").
import type { HomeUi } from "./types";

const ui: HomeUi = {
  "pageT": {
    "badge": "🚀 Platform QR Serba Bisa",
    "h1a": "Buat. Lacak.",
    "h1b": "Analisis.",
    "h1c": "Berkembang.",
    "sub": "QRix membantu Anda membuat QR code andal untuk segala kebutuhan, melacak setiap pindaian secara real-time, dan mengembangkan bisnis dengan lebih cerdas.",
    "cta": "Buat QR Code Pertama Anda",
    "demo": "Tonton Demo",
    "rating": "4.9/5 dari 2.847+ pengguna",
    "cardTitle": "Buat QR Code Anda",
    "cardSub": "Cepat, mudah, dan gratis untuk memulai.",
    "url": "URL",
    "text": "Teks",
    "wifi": "WiFi",
    "vcard": "vCard",
    "more": "Lainnya",
    "enterUrl": "Masukkan URL Anda",
    "enterText": "Masukkan teks Anda",
    "ssid": "Nama jaringan (SSID)",
    "password": "Kata sandi",
    "fullName": "Nama lengkap",
    "phone": "Telepon",
    "emailL": "Email",
    "org": "Perusahaan",
    "emailTo": "Email penerima",
    "subject": "Subjek",
    "body": "Pesan",
    "smsPhone": "Nomor telepon",
    "smsMsg": "Pesan",
    "waPhone": "Nomor WhatsApp (998...)",
    "waMsg": "Pesan (opsional)",
    "tgUser": "Username Telegram (tanpa @)",
    "pin": "Tambahkan Proteksi PIN",
    "pinOpt": "(opsional)",
    "pinPh": "Masukkan PIN 4–10 digit",
    "pinInfo": "Pemindaian akan meminta PIN ini. Membuat tautan dinamis terproteksi.",
    "confirmPin": "Konfirmasi PIN",
    "pinSet": "PIN diatur — akan ditambahkan ke QR code.",
    "generate": "Buat QR Code",
    "generating": "Membuat...",
    "yourQr": "QR Code Anda",
    "dlPng": "Unduh PNG",
    "dlSvg": "Unduh SVG",
    "customize": "Sesuaikan Desain",
    "protected": "Tautan terproteksi PIN dibuat:",
    "designTitle": "Studio Desain QR",
    "qrColor": "Warna QR",
    "bgColor": "Latar Belakang",
    "size": "Ukuran",
    "errLevel": "Koreksi Kesalahan",
    "logo": "Logo",
    "uploadLogo": "Unggah logo",
    "removeLogo": "Hapus",
    "done": "Selesai",
    "statQr": "QR Code Dibuat",
    "statScans": "Total Pindaian",
    "statCountries": "Negara Terjangkau",
    "statBiz": "Bisnis Puas",
    "statUptime": "Uptime & Andal",
    "whyTitle": "Mengapa",
    "whySub": "Semua yang Anda butuhkan untuk membuat, mengelola, dan melacak QR code",
    "f1": "Analitik Real-time",
    "f1d": "Lacak pindaian, lokasi, perangkat, dan lainnya secara real-time.",
    "f2": "QR Code Dinamis",
    "f2d": "Ubah tujuan kapan saja tanpa mengganti QR code.",
    "f3": "Keamanan Canggih",
    "f3d": "Proteksi PIN, masa berlaku, batas, dan anti-spam.",
    "f4": "Kustomisasi Menawan",
    "f4d": "Warna khusus, logo, bingkai, dan desain unik.",
    "toolsTitle": "Semua alat dalam satu tempat",
    "footAbout": "Generator QR code profesional dengan analitik real-time, alat PDF dan gambar — semua dalam satu platform.",
    "footProduct": "Produk",
    "footTools": "Alat",
    "footContact": "Kontak",
    "rights": "Seluruh hak cipta dilindungi."
  },
  "homeFaq": {
    "t": "Pertanyaan yang sering diajukan",
    "s": "Semua yang perlu Anda ketahui sebelum memulai."
  },
  "newsletter": {
    "t": "Tetap terhubung",
    "s": "Alat, panduan, dan tips pertumbuhan baru — sekali sebulan, tanpa spam.",
    "ph": "you@example.com",
    "btn": "Berlangganan",
    "ok": "Berhasil! Segera cek kotak masuk Anda.",
    "err": "Gagal berlangganan — coba lagi."
  },
  "nav": {
    "home": "Beranda",
    "qr": "Alat QR",
    "pdf": "Alat PDF",
    "image": "Alat Gambar",
    "dashboard": "Dasbor",
    "pricing": "Harga",
    "blog": "Blog",
    "ai": "Alat AI",
    "video": "Alat Video",
    "three": "Alat 3D",
    "signin": "Masuk",
    "signout": "Keluar",
    "signup": "Daftar"
  },
  "faq": [
    {
      "q": "Apakah QRix benar-benar gratis?",
      "a": "Ya — semua 185+ alat gratis tanpa watermark dan tanpa perlu daftar. Pro menambahkan QR code dinamis tanpa batas, analitik lebih mendalam, dan pengalaman bebas iklan."
    },
    {
      "q": "Apakah file saya diunggah ke server?",
      "a": "Tidak. Alat PDF, gambar, dan QR berjalan sepenuhnya di browser Anda — file Anda tidak pernah keluar dari perangkat."
    },
    {
      "q": "Apakah QR code saya bisa kedaluwarsa?",
      "a": "QR code statis tidak pernah kedaluwarsa. QR code dinamis tetap aktif selama tautan Anda ada, dan Anda bisa mengubah tujuannya kapan saja."
    },
    {
      "q": "Bisakah saya menambahkan logo dan warna merek ke QR code?",
      "a": "Bisa — Design Studio mendukung logo, warna khusus, bentuk titik, dan bingkai 'Scan me' sambil tetap menjaga QR code mudah dipindai."
    },
    {
      "q": "Apakah QRix berfungsi di ponsel?",
      "a": "Ya — setiap alat responsif dan berjalan di semua browser ponsel modern. Anda juga bisa memasang QRix sebagai aplikasi lewat menu browser Anda."
    },
    {
      "q": "Format apa saja yang bisa saya unduh?",
      "a": "QR code diekspor sebagai PNG atau SVG; PDF, gambar, dan barcode diekspor dalam format asli berkualitas tinggi."
    },
    {
      "q": "Bisakah saya melacak siapa yang memindai QR code saya?",
      "a": "Dengan QR code dinamis, Anda mendapatkan analitik pemindaian secara real-time — total, waktu, perkiraan lokasi, dan perangkat — langsung di dashboard Anda."
    },
    {
      "q": "Apa yang membuat QRix berbeda dari generator QR lainnya?",
      "a": "Ini kotak peralatan lengkap: 30+ jenis QR, studio barcode, halaman link-in-bio, pembuat poster, plus perangkat PDF dan gambar yang lengkap — privat, cepat, dan gratis."
    }
  ]
};

export default ui;
