// GENERATED by scripts/gen-home-i18n-split.mjs — do not edit by hand.
// The ONLY entry point client code may use.
//
// en/ru/uz are authored inline in the components that render them, so they
// resolve to null WITHOUT a network round trip — that is the whole point, and
// it is why the common case now downloads nothing at all. Every other language
// costs one import of its own file (2.8-5.7 KB), never all twelve.
//
// Deferring is safe here in a way it usually is not: `lang` is useState("en")
// hydrated from localStorage in an effect, so every non-English visitor already
// renders English first. This extends a flash that exists today rather than
// introducing one, and a crawler still sees English either way.
import type { HomeUi } from "./types";

export type { HomeUi } from "./types";

/* The languages that live in this directory. en/ru/uz are deliberately absent. */
export const EXTRA_LANGS = ["ar","bn","de","es","fr","hi","id","ja","pt","tr","ur","zh"] as const;

export function hasHomeUi(lang: string): boolean {
  return (EXTRA_LANGS as readonly string[]).includes(lang);
}

/* A literal switch, not import(`./${lang}`): a template import makes the
 * bundler emit every match as a candidate chunk and hides typos until runtime.
 * Returns null for a language served from inline copy. */
export async function loadHomeUi(lang: string): Promise<HomeUi | null> {
  switch (lang) {
    case "ar": return (await import("./ar")).default;
    case "bn": return (await import("./bn")).default;
    case "de": return (await import("./de")).default;
    case "es": return (await import("./es")).default;
    case "fr": return (await import("./fr")).default;
    case "hi": return (await import("./hi")).default;
    case "id": return (await import("./id")).default;
    case "ja": return (await import("./ja")).default;
    case "pt": return (await import("./pt")).default;
    case "tr": return (await import("./tr")).default;
    case "ur": return (await import("./ur")).default;
    case "zh": return (await import("./zh")).default;
    default: return null;
  }
}
