// GENERATED by scripts/gen-home-i18n-split.mjs — do not edit by hand.
// Homepage UI copy — pt. Reached only through loadHomeUi("pt").
import type { HomeUi } from "./types";

const ui: HomeUi = {
  "pageT": {
    "badge": "🚀 A Plataforma de QR Tudo-em-Um",
    "h1a": "Gere. Monitore.",
    "h1b": "Analise.",
    "h1c": "Cresça.",
    "sub": "O QRix ajuda você a criar QR codes poderosos para qualquer finalidade, monitorar cada leitura em tempo real e fazer seu negócio crescer com mais inteligência.",
    "cta": "Crie seu primeiro QR code",
    "demo": "Ver demonstração",
    "rating": "4.9/5 de 2.847+ usuários",
    "cardTitle": "Crie seu QR code",
    "cardSub": "É rápido, fácil e grátis para começar.",
    "url": "URL",
    "text": "Texto",
    "wifi": "WiFi",
    "vcard": "vCard",
    "more": "Mais",
    "enterUrl": "Digite seu URL",
    "enterText": "Digite seu texto",
    "ssid": "Nome da rede (SSID)",
    "password": "Senha",
    "fullName": "Nome completo",
    "phone": "Telefone",
    "emailL": "E-mail",
    "org": "Empresa",
    "emailTo": "E-mail do destinatário",
    "subject": "Assunto",
    "body": "Mensagem",
    "smsPhone": "Número de telefone",
    "smsMsg": "Mensagem",
    "waPhone": "Número do WhatsApp (998...)",
    "waMsg": "Mensagem (opcional)",
    "tgUser": "Usuário do Telegram (sem @)",
    "pin": "Adicionar proteção por PIN",
    "pinOpt": "(opcional)",
    "pinPh": "Digite um PIN de 4 a 10 dígitos",
    "pinInfo": "As leituras exigirão este PIN. Cria um link dinâmico protegido.",
    "confirmPin": "Confirmar PIN",
    "pinSet": "PIN definido — será adicionado ao QR code.",
    "generate": "Gerar QR code",
    "generating": "Criando...",
    "yourQr": "Seu QR code",
    "dlPng": "Baixar PNG",
    "dlSvg": "Baixar SVG",
    "customize": "Personalizar design",
    "protected": "Link protegido por PIN criado:",
    "designTitle": "Estúdio de design de QR",
    "qrColor": "Cor do QR",
    "bgColor": "Fundo",
    "size": "Tamanho",
    "errLevel": "Correção de erros",
    "logo": "Logo",
    "uploadLogo": "Enviar logo",
    "removeLogo": "Remover",
    "done": "Concluído",
    "statQr": "QR codes criados",
    "statScans": "Total de leituras",
    "statCountries": "Países alcançados",
    "statBiz": "Negócios satisfeitos",
    "statUptime": "Disponibilidade e confiança",
    "whyTitle": "Por que",
    "whySub": "Tudo o que você precisa para criar, gerenciar e monitorar QR codes",
    "f1": "Análises em tempo real",
    "f1d": "Monitore leituras, localizações, dispositivos e muito mais em tempo real.",
    "f2": "QR codes dinâmicos",
    "f2d": "Atualize o destino a qualquer momento sem alterar o QR code.",
    "f3": "Segurança avançada",
    "f3d": "Proteção por PIN, expiração, limites e antispam.",
    "f4": "Personalização impecável",
    "f4d": "Cores, logos, molduras e designs exclusivos.",
    "toolsTitle": "Todas as ferramentas em um só lugar",
    "footAbout": "Gerador profissional de QR codes com análises em tempo real, ferramentas de PDF e imagem — tudo em uma só plataforma.",
    "footProduct": "Produto",
    "footTools": "Ferramentas",
    "footContact": "Contato",
    "rights": "Todos os direitos reservados."
  },
  "homeFaq": {
    "t": "Perguntas frequentes",
    "s": "Tudo o que você precisa saber antes de começar."
  },
  "newsletter": {
    "t": "Fique por dentro",
    "s": "Novas ferramentas, guias e dicas de crescimento — uma vez por mês, sem spam.",
    "ph": "you@example.com",
    "btn": "Inscrever-se",
    "ok": "Pronto! Verifique sua caixa de entrada em breve.",
    "err": "Não foi possível inscrever — tente novamente."
  },
  "nav": {
    "home": "Início",
    "qr": "Ferramentas de QR",
    "pdf": "Ferramentas de PDF",
    "image": "Ferramentas de imagem",
    "dashboard": "Painel",
    "pricing": "Preços",
    "blog": "Blog",
    "ai": "Ferramentas de IA",
    "video": "Ferramentas de vídeo",
    "three": "Ferramentas 3D",
    "signin": "Entrar",
    "signout": "Sair",
    "signup": "Criar conta"
  },
  "faq": [
    {
      "q": "O QRix é mesmo gratuito?",
      "a": "Sim — todas as 185+ ferramentas são gratuitas, sem marca d'água e sem cadastro. O Pro acrescenta QR codes dinâmicos ilimitados, análises mais detalhadas e uma experiência sem anúncios."
    },
    {
      "q": "Meus arquivos são enviados para um servidor?",
      "a": "Não. As ferramentas de PDF, imagem e QR funcionam inteiramente no seu navegador — seus arquivos nunca saem do seu dispositivo."
    },
    {
      "q": "Meus QR codes expiram?",
      "a": "Os QR codes estáticos nunca expiram. Os QR codes dinâmicos continuam ativos enquanto o seu link existir, e você pode alterar o destino a qualquer momento."
    },
    {
      "q": "Posso adicionar meu logotipo e as cores da minha marca a um QR code?",
      "a": "Sim — o Design Studio permite logotipos, cores personalizadas, formatos de pontos e molduras 'Scan me', mantendo o código sempre legível."
    },
    {
      "q": "O QRix funciona no celular?",
      "a": "Sim — todas as ferramentas são responsivas e funcionam em qualquer navegador mobile moderno. Você também pode instalar o QRix como app pelo menu do seu navegador."
    },
    {
      "q": "Em quais formatos posso baixar?",
      "a": "Os QR codes são exportados em PNG ou SVG; PDFs, imagens e códigos de barras são exportados em seus formatos nativos de alta qualidade."
    },
    {
      "q": "Consigo saber quem escaneia meu QR code?",
      "a": "Com um QR code dinâmico você tem análises de leitura em tempo real — total de scans, horário, localização aproximada e dispositivos — direto no seu painel."
    },
    {
      "q": "O que diferencia o QRix de outros geradores de QR?",
      "a": "É uma caixa de ferramentas completa: mais de 30 tipos de QR, estúdio de códigos de barras, páginas link-in-bio, criador de pôsteres, além de kits completos de PDF e imagem — privado, rápido e gratuito."
    }
  ]
};

export default ui;
