// GENERATED by scripts/gen-home-i18n-split.mjs — do not edit by hand.
// Homepage UI copy — tr. Reached only through loadHomeUi("tr").
import type { HomeUi } from "./types";

const ui: HomeUi = {
  "pageT": {
    "badge": "🚀 Hepsi Bir Arada QR Platformu",
    "h1a": "Oluştur. İzle.",
    "h1b": "Analiz Et.",
    "h1c": "Büyü.",
    "sub": "QRix, her amaç için güçlü QR kodları oluşturmanıza, her taramayı gerçek zamanlı izlemenize ve işinizi daha akıllıca büyütmenize yardımcı olur.",
    "cta": "İlk QR Kodunu Oluştur",
    "demo": "Demoyu İzle",
    "rating": "2.847+ kullanıcıdan 4.9/5",
    "cardTitle": "QR Kodunu Oluştur",
    "cardSub": "Başlamak hızlı, kolay ve ücretsiz.",
    "url": "URL",
    "text": "Metin",
    "wifi": "WiFi",
    "vcard": "vCard",
    "more": "Daha Fazla",
    "enterUrl": "URL'nizi girin",
    "enterText": "Metninizi girin",
    "ssid": "Ağ adı (SSID)",
    "password": "Parola",
    "fullName": "Ad soyad",
    "phone": "Telefon",
    "emailL": "E-posta",
    "org": "Şirket",
    "emailTo": "Alıcı e-postası",
    "subject": "Konu",
    "body": "Mesaj",
    "smsPhone": "Telefon numarası",
    "smsMsg": "Mesaj",
    "waPhone": "WhatsApp numarası (90...)",
    "waMsg": "Mesaj (isteğe bağlı)",
    "tgUser": "Telegram kullanıcı adı (@ olmadan)",
    "pin": "PIN Koruması Ekle",
    "pinOpt": "(isteğe bağlı)",
    "pinPh": "4–10 haneli PIN girin",
    "pinInfo": "Taramalar bu PIN'i gerektirir. Korumalı bir dinamik bağlantı oluşturur.",
    "confirmPin": "PIN'i Onayla",
    "pinSet": "PIN ayarlandı — QR koduna eklenecek.",
    "generate": "QR Kodu Oluştur",
    "generating": "Oluşturuluyor...",
    "yourQr": "QR Kodunuz",
    "dlPng": "PNG İndir",
    "dlSvg": "SVG İndir",
    "customize": "Tasarımı Özelleştir",
    "protected": "PIN korumalı bağlantı oluşturuldu:",
    "designTitle": "QR Tasarım Stüdyosu",
    "qrColor": "QR Rengi",
    "bgColor": "Arka Plan",
    "size": "Boyut",
    "errLevel": "Hata Düzeltme",
    "logo": "Logo",
    "uploadLogo": "Logo yükle",
    "removeLogo": "Kaldır",
    "done": "Tamam",
    "statQr": "Oluşturulan QR Kodu",
    "statScans": "Toplam Tarama",
    "statCountries": "Ulaşılan Ülke",
    "statBiz": "Mutlu İşletme",
    "statUptime": "Çalışma Süresi & Güvenilir",
    "whyTitle": "Neden",
    "whySub": "QR kodları oluşturmak, yönetmek ve izlemek için ihtiyacınız olan her şey",
    "f1": "Gerçek Zamanlı Analiz",
    "f1d": "Taramaları, konumları, cihazları ve çok daha fazlasını gerçek zamanlı izleyin.",
    "f2": "Dinamik QR Kodları",
    "f2d": "QR kodunu değiştirmeden hedefinizi istediğiniz zaman güncelleyin.",
    "f3": "Gelişmiş Güvenlik",
    "f3d": "PIN koruması, son kullanma tarihi, limitler ve spam koruması.",
    "f4": "Şık Özelleştirme",
    "f4d": "Özel renkler, logolar, çerçeveler ve benzersiz tasarımlar.",
    "toolsTitle": "Tüm araçlar tek yerde",
    "footAbout": "Gerçek zamanlı analiz, PDF ve görsel araçlarıyla profesyonel QR kod oluşturucu — hepsi tek platformda.",
    "footProduct": "Ürün",
    "footTools": "Araçlar",
    "footContact": "İletişim",
    "rights": "Tüm hakları saklıdır."
  },
  "homeFaq": {
    "t": "Sıkça sorulan sorular",
    "s": "Başlamadan önce bilmek isteyebileceğiniz her şey."
  },
  "newsletter": {
    "t": "Gelişmelerden haberdar olun",
    "s": "Yeni araçlar, rehberler ve büyüme ipuçları — ayda bir kez, spam yok.",
    "ph": "you@example.com",
    "btn": "Abone Ol",
    "ok": "Kaydınız alındı! Gelen kutunuzu yakında kontrol edin.",
    "err": "Abone olunamadı — tekrar deneyin."
  },
  "nav": {
    "home": "Ana Sayfa",
    "qr": "QR Araçları",
    "pdf": "PDF Araçları",
    "image": "Görsel Araçları",
    "dashboard": "Panel",
    "pricing": "Fiyatlandırma",
    "blog": "Blog",
    "ai": "AI Araçları",
    "video": "Video Araçları",
    "three": "3D Araçları",
    "signin": "Giriş Yap",
    "signout": "Çıkış Yap",
    "signup": "Kayıt Ol"
  },
  "faq": [
    {
      "q": "QRix gerçekten ücretsiz mi?",
      "a": "Evet — 55'ten fazla aracın tamamı ücretsizdir, filigran yok, kayıt gerekmez. Pro ise sınırsız dinamik QR kodu, daha ayrıntılı analizler ve reklamsız bir deneyim sunar."
    },
    {
      "q": "Dosyalarım bir sunucuya yükleniyor mu?",
      "a": "Hayır. PDF, görsel ve QR araçları tamamen tarayıcınızda çalışır — dosyalarınız cihazınızdan asla çıkmaz."
    },
    {
      "q": "QR kodlarımın süresi doluyor mu?",
      "a": "Statik QR kodlarının süresi hiçbir zaman dolmaz. Dinamik QR kodları ise bağlantınız var olduğu sürece aktif kalır ve hedefini dilediğiniz an değiştirebilirsiniz."
    },
    {
      "q": "QR koduma logomu ve marka renklerimi ekleyebilir miyim?",
      "a": "Evet — Tasarım Stüdyosu, kodu taranabilir tutarken logo, özel renkler, nokta şekilleri ve 'Scan me' çerçevelerini destekler."
    },
    {
      "q": "QRix mobilde çalışıyor mu?",
      "a": "Evet — her araç mobil uyumludur ve her modern mobil tarayıcıda çalışır. Ayrıca QRix'i tarayıcı menüsünden bir uygulama olarak da yükleyebilirsiniz."
    },
    {
      "q": "Hangi formatlarda indirebilirim?",
      "a": "QR kodları PNG veya SVG olarak dışa aktarılır; PDF'ler, görseller ve barkodlar ise kendi yüksek kaliteli formatlarında indirilir."
    },
    {
      "q": "QR kodumu kimlerin taradığını takip edebilir miyim?",
      "a": "Dinamik bir QR kodu ile gerçek zamanlı tarama analizlerine ulaşırsınız — toplam sayı, zaman, yaklaşık konum ve cihazlar panonuzda görünür."
    },
    {
      "q": "QRix diğer QR üreticilerinden ne farkı var?",
      "a": "QRix eksiksiz bir araç kutusudur: 30'dan fazla QR türü, barkod stüdyosu, link-in-bio sayfaları, poster oluşturucu, ayrıca tam kapsamlı PDF ve görsel araçları — gizli, hızlı ve ücretsiz."
    }
  ]
};

export default ui;
