// GENERATED by scripts/gen-home-i18n-split.mjs — do not edit by hand.
// Type only: erased before any bundler sees it, so importing this costs nothing.

export type HomeUi = {
  pageT: Record<string, string>;
  homeFaq: { t: string; s: string };
  newsletter: { t: string; s: string; ph: string; btn: string; ok: string; err: string };
  /* The eight homepage FAQ Q&A. Merged in from what used to be a SECOND
   * twelve-language registry (lib/home-faq-i18n.ts) that the same client
   * component imported alongside this one — so one language now costs one
   * request instead of two whole registries. */
  faq: { q: string; a: string }[];
  /* Read by NO client component. It is the source npm run test:nav diffs
   * lib/nav-i18n.ts against, in both directions — the only thing standing
   * between the site header and silent translation drift. Do not drop it. */
  nav: Record<string, string>;
};
