// GENERATED by scripts/gen-home-i18n-split.mjs — do not edit by hand.
// Homepage UI copy — zh. Reached only through loadHomeUi("zh").
import type { HomeUi } from "./types";

const ui: HomeUi = {
  "pageT": {
    "badge": "🚀 一体化 QR 平台",
    "h1a": "生成。追踪。",
    "h1b": "分析。",
    "h1c": "增长。",
    "sub": "QRix 助你为任何用途创建强大的二维码，实时追踪每一次扫描，让业务增长更聪明。",
    "cta": "创建你的第一个 QR 码",
    "demo": "观看演示",
    "rating": "4.9/5，来自 2,847+ 用户",
    "cardTitle": "创建你的 QR 码",
    "cardSub": "快速、简单，免费上手。",
    "url": "网址",
    "text": "文本",
    "wifi": "WiFi",
    "vcard": "vCard",
    "more": "更多",
    "enterUrl": "输入你的网址",
    "enterText": "输入你的文本",
    "ssid": "网络名称 (SSID)",
    "password": "密码",
    "fullName": "姓名",
    "phone": "电话",
    "emailL": "邮箱",
    "org": "公司",
    "emailTo": "收件人邮箱",
    "subject": "主题",
    "body": "内容",
    "smsPhone": "电话号码",
    "smsMsg": "短信内容",
    "waPhone": "WhatsApp 号码 (998...)",
    "waMsg": "消息（可选）",
    "tgUser": "Telegram 用户名（不含 @）",
    "pin": "添加 PIN 保护",
    "pinOpt": "（可选）",
    "pinPh": "输入 4–10 位 PIN",
    "pinInfo": "扫描时需输入此 PIN，将创建受保护的动态链接。",
    "confirmPin": "确认 PIN",
    "pinSet": "PIN 已设置 — 将添加到 QR 码中。",
    "generate": "生成 QR 码",
    "generating": "生成中...",
    "yourQr": "你的 QR 码",
    "dlPng": "下载 PNG",
    "dlSvg": "下载 SVG",
    "customize": "自定义设计",
    "protected": "已创建 PIN 保护链接：",
    "designTitle": "QR 设计工作室",
    "qrColor": "QR 颜色",
    "bgColor": "背景",
    "size": "尺寸",
    "errLevel": "纠错级别",
    "logo": "标志",
    "uploadLogo": "上传标志",
    "removeLogo": "移除",
    "done": "完成",
    "statQr": "已创建 QR 码",
    "statScans": "总扫描次数",
    "statCountries": "覆盖国家",
    "statBiz": "满意企业",
    "statUptime": "稳定在线可靠",
    "whyTitle": "为什么选择",
    "whySub": "创建、管理和追踪 QR 码所需的一切",
    "f1": "实时分析",
    "f1d": "实时追踪扫描、位置、设备等更多数据。",
    "f2": "动态 QR 码",
    "f2d": "随时更新目标地址，无需更换 QR 码。",
    "f3": "高级安全",
    "f3d": "PIN 保护、有效期、限制与防垃圾保护。",
    "f4": "精美自定义",
    "f4d": "自定义颜色、标志、边框与独特设计。",
    "toolsTitle": "所有工具，一站集成",
    "footAbout": "专业 QR 码生成器，配备实时分析、PDF 与图像工具 — 一个平台，全部搞定。",
    "footProduct": "产品",
    "footTools": "工具",
    "footContact": "联系",
    "rights": "版权所有。"
  },
  "homeFaq": {
    "t": "常见问题",
    "s": "开始之前你可能想了解的一切。"
  },
  "newsletter": {
    "t": "保持关注",
    "s": "新工具、指南与增长技巧 — 每月一次，绝无垃圾邮件。",
    "ph": "you@example.com",
    "btn": "订阅",
    "ok": "订阅成功！请稍后查收邮箱。",
    "err": "订阅失败 — 请重试。"
  },
  "nav": {
    "home": "首页",
    "qr": "QR 工具",
    "pdf": "PDF 工具",
    "image": "图像工具",
    "dashboard": "仪表盘",
    "pricing": "价格",
    "blog": "博客",
    "ai": "AI 工具",
    "video": "视频工具",
    "three": "3D 工具",
    "signin": "登录",
    "signout": "退出",
    "signup": "注册"
  },
  "faq": [
    {
      "q": "QRix 真的免费吗？",
      "a": "是的——全部 185+ 款工具都免费，没有水印，也无需注册。Pro 版则额外提供不限量的动态 QR 码、更深入的数据分析和无广告体验。"
    },
    {
      "q": "我的文件会被上传到服务器吗？",
      "a": "不会。PDF、图片和 QR 工具全部在你的浏览器中运行——你的文件绝不会离开你的设备。"
    },
    {
      "q": "我的 QR 码会过期吗？",
      "a": "静态 QR 码永不过期。动态 QR 码只要链接存在就一直有效，而且你随时可以修改它指向的目标。"
    },
    {
      "q": "我可以给 QR 码加上自己的 Logo 和品牌配色吗？",
      "a": "可以——设计工作室支持添加 Logo、自定义配色、码点形状和「Scan me」外框，同时确保二维码依然能正常扫描。"
    },
    {
      "q": "QRix 能在手机上用吗？",
      "a": "可以——每一款工具都自适应，能在任何现代手机浏览器中使用。你还可以通过浏览器菜单把 QRix 安装为应用。"
    },
    {
      "q": "我可以下载哪些格式？",
      "a": "QR 码可导出为 PNG 或 SVG；PDF、图片和条形码则以各自的高质量原生格式导出。"
    },
    {
      "q": "我能追踪谁扫描了我的 QR 码吗？",
      "a": "使用动态 QR 码，你可以在仪表盘中获得实时扫描分析——总次数、时间、大致位置和设备信息一目了然。"
    },
    {
      "q": "QRix 和其他 QR 生成器有什么不同？",
      "a": "它是一整套工具箱：30+ 种 QR 类型、条形码工作室、link-in-bio 页面、海报制作，再加上完整的 PDF 和图片工具集——私密、快速、免费。"
    }
  ]
};

export default ui;
