/* Regenerates public/fonts/*.woff2 + app/fonts.css from Google Fonts.

   Why we self-host: the render-blocking <link> to fonts.googleapis.com put two
   extra origins in front of first paint — the browser could not even discover
   the font file until our CSS had loaded AND the third-party stylesheet had
   parsed. Measured on production (Lighthouse mobile, simulated throttling) that
   chain cost the LCP font 2637 ms on the homepage and 615 ms on a tool page,
   and the LCP element is a paragraph of text on every template we sampled.
   Self-hosted, the file is same-origin, preloadable from the initial HTML, and
   starts downloading at t=0 in parallel with the stylesheet.

   Only the families that a CSS rule actually renders text with are here. SUSE
   and Poppins are deliberately absent: they appear solely inside ctx.font
   strings in the canvas tools, no CSS rule matches them, and nothing calls
   document.fonts.load() — so the browser never downloaded them and canvas has
   always been drawing in the fallback. Bundling them would not change that.

   The @font-face blocks (incl. every unicode-range) are copied verbatim from
   Google's own CSS so subsetting behaves exactly as before; only the src URL is
   rewritten. Note Bricolage Grotesque has no cyrillic subset — RU/UZ body text
   falls through to Inter, which is why Inter is in this list.

   Run: node scripts/fetch-fonts.mjs
*/
import fs from "node:fs";
import path from "node:path";

const FAMILIES = [
  "Bricolage+Grotesque:opsz,wght@12..96,300;12..96,400;12..96,500;12..96,600;12..96,700;12..96,800",
  "Inter:wght@400;500;600;700;800",
  "Space+Mono:ital,wght@0,400;0,700;1,400",
  "Unbounded:wght@700;800;900",
  "Anton",
  "Oswald:wght@600;700",
];
const CSS_URL =
  "https://fonts.googleapis.com/css2?" +
  FAMILIES.map((f) => `family=${f}`).join("&") +
  "&display=swap";

// woff2 is only served to a UA that advertises support; an old UA gets ttf.
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36";

const OUT_DIR = path.join(process.cwd(), "public", "fonts");
const CSS_OUT = path.join(process.cwd(), "app", "fonts.css");

/* stable local filename: family-subset-style-weight, so a Google version bump
   overwrites in place instead of orphaning the old file in public/. */
function localName(block) {
  const fam = /font-family: '([^']+)'/.exec(block)[1].toLowerCase().replace(/\s+/g, "-");
  const style = /font-style: (\w+)/.exec(block)[1];
  const weight = /font-weight: ([^;]+)/.exec(block)[1].trim().replace(/\s+/g, "-");
  return `${fam}-${style}-${weight}`;
}

const res = await fetch(CSS_URL, { headers: { "User-Agent": UA } });
if (!res.ok) throw new Error(`google fonts css ${res.status}`);
const css = await res.text();

fs.mkdirSync(OUT_DIR, { recursive: true });

const blocks = [...css.matchAll(/\/\* ([a-z-]+) \*\/\s*@font-face \{([\s\S]*?)\}/g)];
if (blocks.length === 0) throw new Error("no @font-face blocks parsed");

const seen = new Map(); // remote url -> local path (families share a file across weights)
const out = [];
let bytes = 0;

for (const [, subset, body] of blocks) {
  const url = /url\((\S+)\)/.exec(body)[1];
  let local = seen.get(url);
  if (!local) {
    local = `/fonts/${localName(body)}-${subset}.woff2`;
    seen.set(url, local);
    const bin = Buffer.from(await (await fetch(url, { headers: { "User-Agent": UA } })).arrayBuffer());
    if (bin.subarray(0, 4).toString("latin1") !== "wOF2") throw new Error(`not woff2: ${url}`);
    fs.writeFileSync(path.join(process.cwd(), "public", local.slice(1)), bin);
    bytes += bin.length;
    console.log(`  ${local}  ${(bin.length / 1024).toFixed(1)} KB`);
  }
  out.push(`/* ${subset} */\n@font-face {${body.replace(/url\(\S+\)/, `url(${local})`)}}`);
}

fs.writeFileSync(
  CSS_OUT,
  `/* GENERATED by scripts/fetch-fonts.mjs — do not edit by hand.\n` +
    `   ${seen.size} woff2 files in public/fonts, ${blocks.length} @font-face rules.\n` +
    `   Re-run when a family or weight changes; see the script header for why we\n` +
    `   self-host and why SUSE/Poppins are not here. */\n\n` +
    out.join("\n\n") +
    "\n",
  "utf8"
);

console.log(`\n${seen.size} files, ${(bytes / 1024).toFixed(0)} KB total → app/fonts.css (${blocks.length} rules)`);
