/* Tool Galaxy data — the 45 functions with their panda icons.
   Icons live in /public/panda (generated by the panda-icons pipeline). */

export type GalaxyItem = {
  slug: string;
  name: string;
  cat: "qr" | "pdf" | "image" | "ai" | "video" | "three";
  color: string;
  icon: string;
  href: string;
};

const CAT_HREF: Record<GalaxyItem["cat"], string> = {
  qr: "/qr-tools", pdf: "/pdf-tools", image: "/image-tools",
  ai: "/ai-tools", video: "/video-tools", three: "/3d-tools",
};

const RAW: [string, string, GalaxyItem["cat"], string][] = [
  ["qr-generator", "QR Generator", "qr", "#22c55e"],
  ["dynamic-qr", "Dynamic QR", "qr", "#22c55e"],
  ["wifi-qr", "WiFi QR", "qr", "#22c55e"],
  ["vcard-qr", "vCard QR", "qr", "#22c55e"],
  ["bulk-qr", "Bulk QR", "qr", "#22c55e"],
  ["qr-scanner", "QR Scanner", "qr", "#22c55e"],
  ["scan-me-frames", "SCAN ME Frames", "qr", "#22c55e"],
  ["utm-builder", "UTM Builder", "qr", "#22c55e"],
  ["merge-pdf", "Merge PDF", "pdf", "#60a5fa"],
  ["compress-pdf", "Compress PDF", "pdf", "#60a5fa"],
  ["pdf-to-word", "PDF to Word", "pdf", "#60a5fa"],
  ["jpg-to-pdf", "JPG to PDF", "pdf", "#60a5fa"],
  ["split-pdf", "Split PDF", "pdf", "#60a5fa"],
  ["ocr-pdf", "OCR PDF", "pdf", "#60a5fa"],
  ["crop-pdf", "Crop PDF", "pdf", "#60a5fa"],
  ["pdf-to-png", "PDF to PNG", "pdf", "#60a5fa"],
  ["remove-bg", "Remove BG", "image", "#c084fc"],
  ["upscale", "Upscale 4x", "image", "#c084fc"],
  ["compress-image", "Compress Image", "image", "#c084fc"],
  ["resize", "Resize", "image", "#c084fc"],
  ["convert", "Convert", "image", "#c084fc"],
  ["photo-editor", "Photo Editor", "image", "#c084fc"],
  ["watermark", "Watermark", "image", "#c084fc"],
  ["exif-remover", "EXIF Remover", "image", "#c084fc"],
  ["logo-maker", "Logo Maker", "ai", "#fbbf24"],
  ["image-generator", "Image Generator", "ai", "#fbbf24"],
  ["prompt-writer", "Prompt Writer", "ai", "#fbbf24"],
  ["resume-builder", "Resume Builder", "ai", "#fbbf24"],
  ["translator", "Translator", "ai", "#fbbf24"],
  ["summarizer", "Summarizer", "ai", "#fbbf24"],
  ["ai-bg-remover", "AI BG Remover", "ai", "#fbbf24"],
  ["compress-video", "Compress Video", "video", "#f472b6"],
  ["trim-video", "Trim Video", "video", "#f472b6"],
  ["gif-maker", "GIF Maker", "video", "#f472b6"],
  ["video-to-mp3", "Video to MP3", "video", "#f472b6"],
  ["mute-video", "Mute Video", "video", "#f472b6"],
  ["speed-changer", "Speed Changer", "video", "#f472b6"],
  ["reverse-video", "Reverse", "video", "#f472b6"],
  ["rotate-video", "Rotate", "video", "#f472b6"],
  ["image-to-3d", "Image to 3D", "three", "#22d3ee"],
  ["3d-viewer", "3D Viewer", "three", "#22d3ee"],
  ["glb-export", "GLB Export", "three", "#22d3ee"],
  ["usdz-ar", "USDZ - AR", "three", "#22d3ee"],
  ["stl-print", "STL for Print", "three", "#22d3ee"],
  ["obj-export", "OBJ Export", "three", "#22d3ee"],
];

export const GALAXY_ITEMS: GalaxyItem[] = RAW.map(([slug, name, cat, color]) => ({
  slug, name, cat, color,
  icon: `/panda/${cat}-${slug}.png`,
  href: CAT_HREF[cat],
}));

/* layout */
export const GRID_COLS = 9;
export const ITEM_SIZE = 2.3;
export const GAP = 0.55;

export function gridDims(count: number) {
  const spacing = ITEM_SIZE + GAP;
  const rows = Math.ceil(count / GRID_COLS);
  return { width: GRID_COLS * spacing, height: rows * spacing, spacing, rows };
}

export function basePos(index: number, count: number) {
  const { width, height, spacing } = gridDims(count);
  const col = index % GRID_COLS;
  const row = Math.floor(index / GRID_COLS);
  return {
    x: col * spacing - width / 2 + spacing / 2,
    y: -(row * spacing) + height / 2 - spacing / 2,
  };
}
